version: "3.5"

services:

  server:
    image: maestro_server:latest
    ports:
      - "$SERVER_PORT:5000"
    restart: on-failure


  ui:
    image: maestro_ui:latest
    ports: 
      - "$UI_PORT:3000"
    tty: true

  streamer_server:
    image: maestro_streamer_server:latest
    ports:
      - "$STREAMER_PORT:4000"
    restart: on-failure